<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="BusTrack.Tests\**" />
    <Content Remove="BusTrack.Tests\**" />
    <None Remove="BusTrack.Tests\**" />

    <Compile Remove="BusTrack.Frontend\BusTrack.Frontend.Server\**" />
    <Content Remove="BusTrack.Frontend\BusTrack.Frontend.Server\**" />
    <None Remove="BusTrack.Frontend\BusTrack.Frontend.Server\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Auth0.ManagementApi" Version="7.10.0" />
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="BenchmarkDotNet" Version="0.13.12" />
    <PackageReference Include="MongoDB.Bson" Version="3.11.1" />
    <PackageReference Include="MongoDB.Driver" Version="3.11.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.SpaProxy" Version="10.0.11" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Selenium.WebDriver" Version="4.20.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.5.1" />
    <PackageReference Include="System.Linq.Async" Version="6.0.1" />
    <PackageReference Include="Moq" Version="4.20.70" />
  </ItemGroup>

</Project>